steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast1-docker.pkg.dev/projectmarkethub-db904/projectmarkethub-repo/app:latest',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}',
      '--build-arg', 'NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}',
      '--build-arg', 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}',
      '.'
    ]
images:
  - 'asia-northeast1-docker.pkg.dev/projectmarkethub-db904/projectmarkethub-repo/app:latest'

substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyD6uAWaLZ6hHgYZpvRrcCKGOZRGWi3ruNU'
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'projectmarkethub-db904.firebaseapp.com'
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'projectmarkethub-db904'
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'projectmarkethub-db904.firebasestorage.app'
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '173689610587'
  _NEXT_PUBLIC_FIREBASE_APP_ID: '1:173689610587:web:ea5e28f0e2e65e6cb43a7e'
  _NEXT_PUBLIC_BASE_URL: 'https://project-market-hub.com'
  _NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_test_51SM2wG8IGGSBqsbGMda1pqXnVHrKQlapODosqa5f2hRDb29Nqdnfh4vTZkKsOMKSlCYO32NQ6jQ0IaPJcckf5Ine00ocvGelY7'
